application: mcottondesign3-hrd
version: clean-23
runtime: python
api_version: 1

builtins:
- datastore_admin: on

derived_file_type:
- python_precompiled

handlers:
- url: /images
  static_dir: templates/_images

- url: /css
  static_dir: templates/_css
  
- url: /js
  static_dir: templates/_js

- url: /favicon.ico
  static_files: templates/_images/favicon.ico
  upload: templates/_images/favicon.ico
  
- url: /robots.txt
  static_files: templates/_images/robots.txt
  upload: templates/_images/favicon.ico

- url: /gae_mini_profiler/static
  static_dir: gae_mini_profiler/static
  
- url: /gae_mini_profiler/.*
  script: gae_mini_profiler/main.py

- url: /.*
  script: main.py
